stages:
    - build
    - test
    - package
    - deploy

job1:
  stage: build
  script:
    - dotnet build

job2:
  stage: test
  script:
    - cd User.Api.UnitTest
    - dotnet test

job3:
  stage: package
  script:
    - cd User.Api
    - docker build -t userapi:test .
    #- docker login -u yasin2020 -p yasin20182018 https://hub.docker.com/
    - docker tag userapi:test 10.211.55:5000/userapi:test
    - docker push 10.211.55:5000/userapi:test
job4:
  stage: deploy
  script:
    - docker run -d -p 8002:80 --link mysql01:db --name userapi 10.211.55:5000/userapi:test